main:mytool1.o mytool2.o main.o
	gcc mytool1.o mytool2.o main.o -o main

main.o:main.c
	gcc -c main.c -o main.o

mytool1.o:mytool1.c
	gcc -c mytool1.c -o mytool1.o

mytool2.o:mytool2.c
	gcc -c mytool2.c -o mytool2.o
